### PR TITLE
Fix klog.V(x) references for klog v2

### PR DESCRIPTION
**Pull request by dims**
klog.V(x) is no longer a boolean. We need to use the `.Enabled()` method

### CODE REVIEW

**Comment by dims** [comment]
/assign @bowei @spencerhance 

cc @tanjunchen @serathius

**Comment by tanjunchen** [comment]
get it

**Comment by bowei** [comment]
This is not quite sufficient -- you need to fix references in the code generator.

**Comment by bowei** [comment]
https://github.com/GoogleCloudPlatform/k8s-cloud-provider/compare/master...bowei:fix-klog?expand=1

**Comment by dims** [comment]
@bowei thanks! pulled in your two commits.

**Pull request merged**
