### PR TITLE
add hooks for attaching and detaching disks

### PR DESCRIPTION
**Pull request by hantaowang**
Adds two hooks that allows mocking of the AttachDisk and DetachDisk cloud functions, to be used for unit testing k/legacy-cloud-providers.

See: https://github.com/kubernetes/kubernetes/pull/80735

@davidz627 @jingxu97

### CODE REVIEW

**Comment by hantaowang** [comment]
@spencerhance

**Comment by spencerhance** [comment]
@bowei Looks like I'm unable to merge, can you take a look?

**Comment by hantaowang** [comment]
Can we make a new release so the dep in k/k can be updated?

**Comment by spencerhance** [comment]
@hantaowang just released 1.8.0

**Comment by hantaowang** [comment]
thank you!

**Pull request merged**
