### PR TITLE
Adds checkcov to the build

### PR DESCRIPTION
**Pull request by bowei**
Adds a simple script for checking code coverage
    
    `checkcov` takes as input the output of "go test -cover ..." and a checkcov
    YAML file containing expected coverage limits.
    
    Usage
    
    $ go test -cover ./pkg/...  > cov.out
    $ go run tools/checkcov.go -configFile checkcov.yaml -covFile cov.out

### CODE REVIEW

**Comment by bowei** [comment]
@swetharepakula

**Review by swetharepakula — APPROVED** [review]

**Pull request merged**
