### PR TITLE
Add utils functions for RelativeResourceNameWithVersion

### PR DESCRIPTION
**Pull request by spencerhance**
This func generates a string very similar to a SelfLink but without including the "googleapis.com" endpoint."

### CODE REVIEW

**Comment by bowei** [comment]
Let's discuss -- how are we going to use the new function? Don't we need to make the http://googleapis.com... configurable for all instances?

**Comment by spencerhance** [comment]
Closing in favor of https://github.com/GoogleCloudPlatform/k8s-cloud-provider/pull/79

**Pull request closed without merging**
