### PR TITLE
feat: add managedinstancegroups

### PR DESCRIPTION
**Pull request by charlie-haley**
This PR adds support for MIGs as well as updating some dependencies

### CODE REVIEW

**Comment by bowei** [comment]
reviewing -- generally change looks ok

**Comment by bowei** [comment]
I'm getting some build errors with your patch:

```
pkg/cloud/gen.go:18459:60: too many arguments in call to g.s.GA.InstanceTemplates.Get
	have (string, string, string)
	want (string, string)
pkg/cloud/gen.go:18480:51: too many arguments in call to g.s.GA.InstanceTemplates.List
	have (string, string)
	want (string)
pkg/cloud/gen.go:18528:63: too many arguments in call to g.s.GA.InstanceTemplates.Insert
	have (string, string, *"google.golang.org/api/compute/v1".InstanceTemplate)
	want (string, *"google.golang.org/api/compute/v1".InstanceTemplate)
pkg/cloud/gen.go:18561:63: too many arguments in call to g.s.GA.InstanceTemplates.Delete
	have (string, string, string)
	want (string, string)
```

**Comment by charlie-haley** [comment]
> I'm getting some build errors with your patch:
> 
> ```
> pkg/cloud/gen.go:18459:60: too many arguments in call to g.s.GA.InstanceTemplates.Get
> 	have (string, string, string)
> 	want (string, string)
> pkg/cloud/gen.go:18480:51: too many arguments in call to g.s.GA.InstanceTemplates.List
> 	have (string, string)
> 	want (string)
> pkg/cloud/gen.go:18528:63: too many arguments in call to g.s.GA.InstanceTemplates.Insert
> 	have (string, string, *"google.golang.org/api/compute/v1".InstanceTemplate)
> 	want (string, *"google.golang.org/api/compute/v1".InstanceTemplate)
> pkg/cloud/gen.go:18561:63: too many arguments in call to g.s.GA.InstanceTemplates.Delete
> 	have (string, string, string)
> 	want (string, string)
> ```

Sorry had the wrong keyType specified! Should be all working now

**Comment by nsilve** [comment]
@charlie-haley do you need any help to progress with that?

**Comment by charlie-haley** [comment]
> @charlie-haley do you need any help to progress with that?

The tests pass locally, it seems like a /retest needs running in the CI which I'm unable to do, only @bowei has permission to do that

**Comment by nsilve** [comment]
I believe that it would be helpful to resolve the conflicts to make the branch ready to be merged when tests pass.

**Comment by bowei** [comment]
This needs to be updated so it's mergeable -- can you ping once that is done?

**Comment by charlie-haley** [comment]
Should be up to date now @bowei

**Comment by harveyxia** [comment]
Gentle bump, we've got a downstream dependency on this PR. Thank you for putting this together!

**Comment by harveyxia** [comment]
Any updates here?

**Comment by bowei** [comment]
Support has been added. Thanks for your original PR.

**Pull request closed without merging**
