### PR TITLE
Update version of google.golang.org/api to 0.45.0

### PR DESCRIPTION
**Pull request by sdmodi**
We need to update the google.golang.org/api to the latest version for IPv6 changes. Here are the steps that I ran:

Update go.mod:
google.golang.org/api v0.45.0
google.golang.org/api => google.golang.org/api v0.45.0
Run 'go mod tidy'
Run 'make gen'
Run 'go mod vendor'

### CODE REVIEW

**Comment by sdmodi** [comment]
@bowei do I need a review from someone else as well? This is still blocked for me and says "Review Required"

**Comment by bowei** [comment]
apparently the google bot isn't working, let me ask

**Review by bowei — APPROVED** [review]

**Comment by sdmodi** [comment]
Thanks @bowei. This unblocks me.

**Pull request merged**
