### PR TITLE
Add support for TargetTcpProxy

### PR DESCRIPTION
**Pull request by andraxylia**

### CODE REVIEW

**Comment by bowei** [comment]
actually /hold

is this missing some of the generated files? I only see mock

**Comment by spencerhance** [comment]
@andraxylia Please run `make` to generate the files

**Comment by andraxylia** [comment]
I added also alpha version + generated files.

**Comment by bowei** [comment]
can you squash all of your commits and clean up the commit message

Use this format for commit message: https://chris.beams.io/posts/git-commit/

**Comment by andraxylia** [comment]
Sure, but note the admins can do the "squash and merge" when merging the PR.

**Comment by andraxylia** [comment]
You may need to configure it though:
https://help.github.com/en/github/administering-a-repository/configuring-commit-squashing-for-pull-requests

**Comment by bowei** [comment]
That will result in a strange commit message, so it's better if the merge is done by hand.

**Comment by andraxylia** [comment]
Done, PTAL.

**Pull request merged**
